# Generated by Django 6.0.5 on 2026-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(max_length=30, verbose_name='Gender')),
                ('source', models.CharField(max_length=60, verbose_name='Heard From')),
                ('mobile', models.CharField(db_index=True, max_length=15, verbose_name='Mobile Number')),
                ('coupon_code', models.CharField(default='NEW50', max_length=20, verbose_name='Coupon Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date & Time')),
            ],
            options={
                'verbose_name': 'User Lead',
                'verbose_name_plural': 'User Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
